filename: app-test
spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  kafka:
    bootstrap-servers: kafka:9092
  
  datasource:
    url: jdbc:mysql://localhost:33306/junit_local_tri_base
    username: junit_local
    password: password

socnet:
  vk:
    appId: 123
    secretKey: secretKey