filename: app-test
spring:

  datasource:
    url: jdbc:mysql://localhost:13306/junit_database
    username: junit_user
    password: junit_password

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      group-id: group_id_1

alerter:
  telegram:
    chatId: -1001958935656
    token: 1194574646:AAEWS0EP5ABnnFITO924snE30pcD9284Hbc

socnet:
  vk:
    appId: 123456789
    secretKey: "vk_secret_key"