filename: app
spring:

  application:
    name: users-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092

  profiles:
    group:
      home: local, suppress_useless_logs, home
      local: local, suppress_useless_logs

logging:
  level:
    root: info

alerter:
  telegram:
    chatId: ${TELEGRAM_CHAT_ID}
    token: ${TELEGRAM_TOKEN}

socnet:
  vk:
    appId: ${VK_APP_ID}
    secretKey: ${VK_SECRET_KEY}
