filename: app
spring:

  application:
    name: users-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection_timeout: 500000
      connectionTimeout: 500000
      networkTimeout: 12314556

  kafka:
    auto-offset-reset: earliest
    bootstrap-servers: kafka:9092
    consumer:
      trusted_packages: "m3.users.dto.rq"
    topicName: 'topic-users'

logging:
  level:
    root: info

alerter:
  telegram:
    chatId: ${TELEGRAM_CHAT_ID}
    token: ${TELEGRAM_TOKEN}

socnet:
  vk:
    appId: ${VK_APP_ID}
    secretKey: ${VK_SECRET_KEY}
