filename: app
spring:
  kafka:
    bootstrap-servers: kafka:9092

  datasource:
    url: ${DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

socnet:
  vk:
    appId: ${VK_APP_ID}
    secretKey: ${VK_SECRET_KEY}