filename: app-test
spring:
  datasource:
    url: jdbc:mysql://localhost:33306/junit_database
    username: junit_user
    password: junit_password

  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration