filename: app-test
spring:

  datasource:
    url: jdbc:mysql://localhost:13306/junit_database
    username: junit_user
    password: junit_password

  kafka:
    bootstrap-servers: kafka:29092

alerter:
  telegram:
    chatId: -1234567890123
    token: 1234567890:THISISATESTATOKENABCDEFGHUJIKLMNOPQ

socnet:
  vk:
    appId: 123456789
    secretKey: "vk_secret_key"